# ═══════════════════════════════════════════════════════════════════
# ZapPhysics — VisualizeEnhanced: Interactive HTML+Canvas visualization
# Enhanced with zoom/pan/time slider/trails
# ═══════════════════════════════════════════════════════════════════

# ── Enhanced Orbital Visualization with zoom/pan/time slider/trails ──

fn orbital_viz_interactive(particles_data, energy_history, title)
  let canvas_w = 800
  let canvas_h = 600
  let body = "<div class='container'>"
  body = body + "<div class='chart-box'>"
  body = body + "<canvas id='orbitCanvas' width='" + str(canvas_w) + "' height='" + str(canvas_h) + "'></canvas>"
  body = body + "<div class='controls'>"
  body = body + "<label>Time: <span id='timeDisplay'>0</span></label>"
  body = body + "<input type='range' id='timeSlider' min='0' max='" + str(len(energy_history) - 1) + "' value='0' step='1'>"
  body = body + "<button onclick='playPause()'>Play/Pause</button>"
  body = body + "<button onclick='resetView()'>Reset View</button>"
  body = body + "<button onclick='toggleTrails()'>Trails: ON</button>"
  body = body + "</div>"
  body = body + "</div>"
  body = body + "<div class='chart-box'>"
  body = body + "<canvas id='energyChart' width='400' height='300'></canvas>"
  body = body + "</div>"
  body = body + "<div class='chart-box'>"
  body = body + "<canvas id='infoChart' width='400' height='300'></canvas>"
  body = body + "</div>"
  body = body + "</div>"
  body = body + "<div class='legend' id='legend'></div>"

  let js_data = "const particleData = " + json_stringify(particles_data) + ";"
  let js_energy = "const energyData = " + json_stringify(energy_history) + ";"

  let js = "<script>"
  js = js + js_data
  js = js + js_energy
  js = js + "const canvas = document.getElementById('orbitCanvas');"
  js = js + "const ctx = canvas.getContext('2d');"
  js = js + "const energyCtx = document.getElementById('energyChart').getContext('2d');"
  js = js + "const infoCtx = document.getElementById('infoChart').getContext('2d');"
  js = js + "const timeSlider = document.getElementById('timeSlider');"
  js = js + "const timeDisplay = document.getElementById('timeDisplay');"
  js = js + "let scale = 20;"
  js = js + "let offsetX = canvas.width / 2;"
  js = js + "let offsetY = canvas.height / 2;"
  js = js + "let isPanning = false;"
  js = js + "let lastMouseX = 0;"
  js = js + "let lastMouseY = 0;"
  js = js + "let showTrails = true;"
  js = js + "let isPlaying = false;"
  js = js + "let playInterval = null;"
  js = js + "let currentFrame = 0;"
  js = js + "let maxFrames = energyData.length;"
  js = js + "let trailHistory = {};"
  js = js + "for (let p of particleData) { trailHistory[p.name] = []; }"

  js = js + "function worldToScreen(x, y) {"
  js = js + "return { x: x * scale + offsetX, y: canvas.height - (y * scale + offsetY) };"
  js = js + "}"

  js = js + "function screenToWorld(x, y) {"
  js = js + "return { x: (x - offsetX) / scale, y: (canvas.height - y - offsetY) / scale };"
  js = js + "}"

  js = js + "function draw() {"
  js = js + "ctx.clearRect(0, 0, canvas.width, canvas.height);"

  js = js + "// Draw grid"
  js = js + "ctx.strokeStyle = '#333';"
  js = js + "ctx.lineWidth = 0.5;"
  js = js + "for (let i = -20; i <= 20; i++) {"
  js = js + "let x = i * 50 * scale + offsetX;"
  js = js + "ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, canvas.height); ctx.stroke();"
  js = js + "let y = canvas.height - (i * 50 * scale + offsetY);"
  js = js + "ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(canvas.width, y); ctx.stroke();"
  js = js + "}"

  js = js + "// Draw trails"
  js = js + "if (showTrails) {"
  js = js + "for (let p of particleData) {"
  js = js + "let trail = trailHistory[p.name];"
  js = js + "if (trail.length > 1) {"
  js = js + "ctx.strokeStyle = p.color + '40';"
  js = js + "ctx.lineWidth = 1;"
  js = js + "ctx.beginPath();"
  js = js + "for (let i = 1; i < trail.length; i++) {"
  js = js + "let s1 = worldToScreen(trail[i-1].x, trail[i-1].y);"
  js = js + "let s2 = worldToScreen(trail[i].x, trail[i].y);"
  js = js + "ctx.moveTo(s1.x, s1.y);"
  js = js + "ctx.lineTo(s2.x, s2.y);"
  js = js + "}"
  js = js + "ctx.stroke();"
  js = js + "}"
  js = js + "}"
  js = js + "}"

  js = js + "// Draw particles at current frame"
  js = js + "for (let p of particleData) {"
  js = js + "let pos = p.positions[currentFrame] || p;"
  js = js + "let s = worldToScreen(pos.x, pos.y);"
  js = js + "let r = Math.max(pos.radius || 3, 3);"
  js = js + "// Glow"
  js = js + "let grad = ctx.createRadialGradient(s.x, s.y, 0, s.x, s.y, r * 3);"
  js = js + "grad.addColorStop(0, p.color);"
  js = js + "grad.addColorStop(1, 'transparent');"
  js = js + "ctx.fillStyle = grad;"
  js = js + "ctx.beginPath(); ctx.arc(s.x, s.y, r * 3, 0, 6.28); ctx.fill();"
  js = js + "// Core"
  js = js + "ctx.fillStyle = p.color;"
  js = js + "ctx.beginPath(); ctx.arc(s.x, s.y, r, 0, 6.28); ctx.fill();"
  js = js + "// Label"
  js = js + "ctx.fillStyle = '#fff';"
  js = js + "ctx.font = '12px monospace';"
  js = js + "ctx.fillText(p.name, s.x + 10, s.y - 10);"
  js = js + "// Update trail history"
  js = js + "updateTrail(p.name, pos.x, pos.y);"
  js = js + "}"

  js = js + "drawEnergyChart();"
  js = js + "drawInfoChart();"
  js = js + "updateLegend();"
  js = js + "}"

  js = js + "function drawEnergyChart() {"
  js = js + "energyCtx.clearRect(0, 0, 400, 300);"
  js = js + "energyCtx.fillStyle = '#16213e';"
  js = js + "energyCtx.fillRect(0, 0, 400, 300);"
  js = js + "if (energyData.length < 2) return;"
  js = js + "const minE = Math.min.apply(null, energyData);"
  js = js + "const maxE = Math.max.apply(null, energyData);"
  js = js + "const range = maxE - minE || 1;"
  js = js + "energyCtx.strokeStyle = '#e94560';"
  js = js + "energyCtx.lineWidth = 2;"
  js = js + "energyCtx.beginPath();"
  js = js + "for (let i = 0; i < energyData.length; i++) {"
  js = js + "const x = 40 + (i / (energyData.length - 1)) * 340;"
  js = js + "const y = 270 - ((energyData[i] - minE) / range) * 220;"
  js = js + "if (i === 0) energyCtx.moveTo(x, y);"
  js = js + "else energyCtx.lineTo(x, y);"
  js = js + "}"
  js = js + "energyCtx.stroke();"
  js = js + "// Current frame marker"
  js = js + "const cx = 40 + (currentFrame / (maxFrames - 1)) * 340;"
  js = js + "const cy = 270 - ((energyData[currentFrame] - minE) / range) * 220;"
  js = js + "energyCtx.fillStyle = '#fff';"
  js = js + "energyCtx.beginPath(); energyCtx.arc(cx, cy, 5, 0, 6.28); energyCtx.fill();"
  js = js + "energyCtx.fillStyle = '#e0e0e0';"
  js = js + "energyCtx.font = '14px monospace';"
  js = js + "energyCtx.fillText('Energy Conservation', 130, 20);"
  js = js + "energyCtx.fillText('Initial: ' + energyData[0].toFixed(2), 10, 290);"
  js = js + "energyCtx.fillText('Current: ' + energyData[currentFrame].toFixed(2), 130, 290);"
  js = js + "}"

  js = js + "function drawInfoChart() {"
  js = js + "infoCtx.clearRect(0, 0, 400, 300);"
  js = js + "infoCtx.fillStyle = '#16213e';"
  js = js + "infoCtx.fillRect(0, 0, 400, 300);"
  js = js + "infoCtx.fillStyle = '#e0e0e0';"
  js = js + "infoCtx.font = '14px monospace';"
  js = js + "let y = 30;"
  js = js + "for (let p of particleData) {"
  js = js + "let pos = p.positions[currentFrame] || p;"
  js = js + "infoCtx.fillStyle = p.color;"
  js = js + "infoCtx.fillText(p.name + ': (' + pos.x.toFixed(2) + ', ' + pos.y.toFixed(2) + ')', 10, y);"
  js = js + "y += 20;"
  js = js + "}"
  js = js + "infoCtx.fillText('Frame: ' + currentFrame + ' / ' + maxFrames, 10, y + 20);"
  js = js + "infoCtx.fillText('Scale: ' + scale.toFixed(1), 10, y + 40);"
  js = js + "}"

  js = js + "function updateLegend() {"
  js = js + "let html = '';"
  js = js + "for (let p of particleData) {"
  js = js + "html += '<span style=\"color:' + p.color + '\">■</span> ' + p.name + '  ';"
  js = js + "}"
  js = js + "document.getElementById('legend').innerHTML = html;"
  js = js + "}"

  js = js + "function updateTrail(name, x, y) {"
  js = js + "if (!trailHistory[name]) trailHistory[name] = [];"
  js = js + "trailHistory[name].push({x, y});"
  js = js + "if (trailHistory[name].length > 200) trailHistory[name].shift();"
  js = js + "}"

  js = js + "function playPause() {"
  js = js + "isPlaying = !isPlaying;"
  js = js + "if (isPlaying) {"
  js = js + "playInterval = setInterval(() => {"
  js = js + "currentFrame = (currentFrame + 1) % maxFrames;"
  js = js + "timeSlider.value = currentFrame;"
  js = js + "timeDisplay.textContent = currentFrame;"
  js = js + "draw();"
  js = js + "}, 50);"
  js = js + "} else {"
  js = js + "clearInterval(playInterval);"
  js = js + "}"
  js = js + "}"

  js = js + "function resetView() {"
  js = js + "scale = 20;"
  js = js + "offsetX = canvas.width / 2;"
  js = js + "offsetY = canvas.height / 2;"
  js = js + "draw();"
  js = js + "}"

  js = js + "function toggleTrails() {"
  js = js + "showTrails = !showTrails;"
  js = js + "document.querySelector('button:nth-child(4)').textContent = 'Trails: ' + (showTrails ? 'ON' : 'OFF');"
  js = js + "draw();"
  js = js + "}"

  // Mouse interaction
  js = js + "canvas.addEventListener('mousedown', (e) => {"
  js = js + "isPanning = true;"
  js = js + "lastMouseX = e.clientX;"
  js = js + "lastMouseY = e.clientY;"
  js = js + "canvas.style.cursor = 'grabbing';"
  js = js + "});"

  js = js + "canvas.addEventListener('mousemove', (e) => {"
  js = js + "if (!isPanning) return;"
  js = js + "let dx = e.clientX - lastMouseX;"
  js = js + "let dy = e.clientY - lastMouseY;"
  js = js + "offsetX += dx;"
  js = js + "offsetY -= dy;"
  js = js + "lastMouseX = e.clientX;"
  js = js + "lastMouseY = e.clientY;"
  js = js + "draw();"
  js = js + "});"

  js = js + "canvas.addEventListener('mouseup', () => {"
  js = js + "isPanning = false;"
  js = js + "canvas.style.cursor = 'crosshair';"
  js = js + "});"

  js = js + "canvas.addEventListener('wheel', (e) => {"
  js = js + "e.preventDefault();"
  js = js + "let zoomFactor = e.deltaY > 0 ? 0.9 : 1.1;"
  js = js + "let mouseX = e.clientX - canvas.getBoundingClientRect().left;"
  js = js + "let mouseY = e.clientY - canvas.getBoundingClientRect().top;"
  js = js + "let worldBefore = screenToWorld(mouseX, mouseY);"
  js = js + "scale *= zoomFactor;"
  js = js + "scale = Math.max(1, Math.min(scale, 200));"
  js = js + "let worldAfter = screenToWorld(mouseX, mouseY);"
  js = js + "offsetX += (worldAfter.x - worldBefore.x) * scale;"
  js = js + "offsetY += (worldAfter.y - worldBefore.y) * scale;"
  js = js + "draw();"
  js = js + "}, { passive: false });"

  js = js + "timeSlider.addEventListener('input', (e) => {"
  js = js + "currentFrame = parseInt(e.target.value);"
  js = js + "timeDisplay.textContent = currentFrame;"
  js = js + "draw();"
  js = js + "});"

  js = js + "draw();"
  js = js + "updateLegend();"
  js = js + "</script>"

  html_page(title, body, js)

# ── Save Visualization to File ──

fn save_viz(html_content, filename)
  json_save(filename, {"html": html_content, "type": "visualization"})
  say("Visualization saved to " + filename + " (as JSON with 'html' field)")
  say("Open the file and extract the 'html' field, or use serve_viz() to serve it live")