# ═══════════════════════════════════════════════════════════════════
# ZapPhysics — Visualize: HTML+Canvas visualization via built-in HTTP
# Generates interactive visualizations served through Zap's built-in
# web server. Zap is both backend (physics computation) and frontend
# (HTML/Canvas rendering served via http_server).
# ═══════════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════════
# ZapPhysics — Visualize: HTML+Canvas visualization via built-in HTTP
# Generates interactive visualizations served through Zap's built-in
# web server. Zap is both backend (physics computation) and frontend
# (HTML/Canvas rendering served via http_server).
# ═══════════════════════════════════════════════════════════════════

# ── HTML Page Generator ──
# Generates a complete HTML page with Canvas for visualization

fn html_page(title, body_content, extra_js)
  let html = "<!DOCTYPE html>"
  html = html + "<html><head><title>" + title + "</title>"
  html = html + "<meta charset='utf-8'>"
  html = html + "<style>"
  html = html + "body { margin: 0; padding: 20px; font-family: monospace; background: #1a1a2e; color: #e0e0e0; }"
  html = html + "canvas { background: #0f0f23; border: 1px solid #333; cursor: crosshair; touch-action: none; }"
  html = html + ".container { display: flex; gap: 20px; flex-wrap: wrap; }"
  html = html + ".chart-box { background: #16213e; padding: 15px; border-radius: 8px; margin: 10px; }"
  html = html + ".info { padding: 10px; background: #0f3460; border-radius: 5px; margin: 5px 0; }"
  html = html + "button { padding: 8px 16px; margin: 5px; background: #e94560; color: white; border: none; border-radius: 4px; cursor: pointer; }"
  html = html + "button:hover { background: #c73e54; }"
  html = html + ".controls { background: #0f3460; padding: 15px; border-radius: 8px; margin: 10px; }"
  html = html + "input[type=range] { width: 300px; margin: 5px; }"
  html = html + "label { margin-right: 10px; }"
  html = html + ".legend { font-size: 12px; color: #aaa; margin-top: 5px; }"
  html = html + "</style></head><body>"
  html = html + "<h1>" + title + "</h1>"
  html = html + body_content
  html = html + extra_js
  html = html + "</body></html>"
  html

# ── Orbital Visualization (Enhanced with zoom/pan/trails/time slider) ──
fn orbital_viz_html(particles_data, energy_history, title)
  let canvas_w = 800
  let canvas_h = 600
  let body = "<div class='container'>"
  body = body + "<div class='chart-box'>"
  body = body + "<canvas id='orbitCanvas' width='" + str(canvas_w) + "' height='" + str(canvas_h) + "'></canvas>"
  body = body + "<div class='controls'>"
  body = body + "<label>Time: <span id='timeDisplay'>0</span></label>"
  body = body + "<input type='range' id='timeSlider' min='0' max='" + str(len(energy_history) - 1) + "' value='0' step='1'>"
  body = body + "<button onclick='playPause()'>Play/Pause</button>"
  body = body + "<button onclick='resetView()'>Reset View</button>"
  body = body + "<button onclick='toggleTrails()'>Trails: ON</button>"
  body = body + "</div>"
  body = body + "</div>"
  body = body + "<div class='chart-box'>"
  body = body + "<canvas id='energyChart' width='400' height='300'></canvas>"
  body = body + "</div>"
  body = body + "<div class='chart-box'>"
  body = body + "<canvas id='infoChart' width='400' height='300'></canvas>"
  body = body + "</div>"
  body = body + "</div>"
  body = body + "<div class='legend' id='legend'></div>"

  let js_data = "const particleData = " + json_stringify(particles_data) + ";"
  let js_energy = "const energyData = " + json_stringify(energy_history) + ";"

  let js = "<script>"
  js = js + js_data
  js = js + js_energy
  js = js + "const canvas = document.getElementById('orbitCanvas');"
  js = js + "const ctx = canvas.getContext('2d');"
  js = js + "const energyCtx = document.getElementById('energyChart').getContext('2d');"
  js = js + "const infoCtx = document.getElementById('infoChart').getContext('2d');"
  js = js + "const timeSlider = document.getElementById('timeSlider');"
  js = js + "const timeDisplay = document.getElementById('timeDisplay');"
  js = js + "let scale = 20;"
  js = js + "let offsetX = canvas.width / 2;"
  js = js + "let offsetY = canvas.height / 2;"
  js = js + "let isPanning = false;"
  js = js + "let lastMouseX = 0;"
  js = js + "let lastMouseY = 0;"
  js = js + "let showTrails = true;"
  js = js + "let isPlaying = false;"
  js = js + "let playInterval = null;"
  js = js + "let currentFrame = 0;"
  js = js + "let maxFrames = energyData.length;"
  js = js + "let trailHistory = {};"
  js = js + "for (let p of particleData) { trailHistory[p.name] = []; }"

  js = js + "function worldToScreen(x, y) {"
  js = js + "return { x: x * scale + offsetX, y: canvas.height - (y * scale + offsetY) };"
  js = js + "}"

  js = js + "function screenToWorld(x, y) {"
  js = js + "return { x: (x - offsetX) / scale, y: (canvas.height - y - offsetY) / scale };"
  js = js + "}"

  js = js + "function draw() {"
  js = js + "ctx.clearRect(0, 0, canvas.width, canvas.height);"

  js = js + "// Draw grid"
  js = js + "ctx.strokeStyle = '#333';"
  js = js + "ctx.lineWidth = 0.5;"
  js = js + "for (let i = -20; i <= 20; i++) {"
  js = js + "let x = i * 50 * scale + offsetX;"
  js = js + "ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, canvas.height); ctx.stroke();"
  js = js + "let y = canvas.height - (i * 50 * scale + offsetY);"
  js = js + "ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(canvas.width, y); ctx.stroke();"
  js = js + "}"

  js = js + "// Draw trails"
  js = js + "if (showTrails) {"
  js = js + "for (let p of particleData) {"
  js = js + "let trail = trailHistory[p.name];"
  js = js + "if (trail.length > 1) {"
  js = js + "ctx.strokeStyle = p.color + '40';"
  js = js + "ctx.lineWidth = 1;"
  js = js + "ctx.beginPath();"
  js = js + "for (let i = 1; i < trail.length; i++) {"
  js = js + "let s1 = worldToScreen(trail[i-1].x, trail[i-1].y);"
  js = js + "let s2 = worldToScreen(trail[i].x, trail[i].y);"
  js = js + "ctx.moveTo(s1.x, s1.y);"
  js = js + "ctx.lineTo(s2.x, s2.y);"
  js = js + "}"
  js = js + "ctx.stroke();"
  js = js + "}"
  js = js + "}"
  js = js + "}"

  js = js + "// Draw particles at current frame"
  js = js + "for (let p of particleData) {"
  js = js + "let pos = p.positions[currentFrame] || p;"
  js = js + "let s = worldToScreen(pos.x, pos.y);"
  js = js + "let r = Math.max(pos.radius || 3, 3);"
  js = js + "// Glow"
  js = js + "let grad = ctx.createRadialGradient(s.x, s.y, 0, s.x, s.y, r * 3);"
  js = js + "grad.addColorStop(0, p.color);"
  js = js + "grad.addColorStop(1, 'transparent');"
  js = js + "ctx.fillStyle = grad;"
  js = js + "ctx.beginPath(); ctx.arc(s.x, s.y, r * 3, 0, 6.28); ctx.fill();"
  js = js + "// Core"
  js = js + "ctx.fillStyle = p.color;"
  js = js + "ctx.beginPath(); ctx.arc(s.x, s.y, r, 0, 6.28); ctx.fill();"
  js = js + "// Label"
  js = js + "ctx.fillStyle = '#fff';"
  js = js + "ctx.font = '12px monospace';"
  js = js + "ctx.fillText(p.name, s.x + 10, s.y - 10);"
  js = js + "}"

  js = js + "drawEnergyChart();"
  js = js + "drawInfoChart();"
  js = js + "updateLegend();"
  js = js + "}"

  js = js + "function drawEnergyChart() {"
  js = js + "energyCtx.clearRect(0, 0, 400, 300);"
  js = js + "energyCtx.fillStyle = '#16213e';"
  js = js + "energyCtx.fillRect(0, 0, 400, 300);"
  js = js + "if (energyData.length < 2) return;"
  js = js + "const minE = Math.min.apply(null, energyData);"
  js = js + "const maxE = Math.max.apply(null, energyData);"
  js = js + "const range = maxE - minE || 1;"
  js = js + "energyCtx.strokeStyle = '#e94560';"
  js = js + "energyCtx.lineWidth = 2;"
  js = js + "energyCtx.beginPath();"
  js = js + "for (let i = 0; i < energyData.length; i++) {"
  js = js + "const x = 40 + (i / (energyData.length - 1)) * 340;"
  js = js + "const y = 270 - ((energyData[i] - minE) / range) * 220;"
  js = js + "if (i === 0) energyCtx.moveTo(x, y);"
  js = js + "else energyCtx.lineTo(x, y);"
  js = js + "}"
  js = js + "energyCtx.stroke();"
  js = js + "// Current frame marker"
  js = js + "const cx = 40 + (currentFrame / (maxFrames - 1)) * 340;"
  js = js + "const cy = 270 - ((energyData[currentFrame] - minE) / range) * 220;"
  js = js + "energyCtx.fillStyle = '#fff';"
  js = js + "energyCtx.beginPath(); energyCtx.arc(cx, cy, 5, 0, 6.28); energyCtx.fill();"
  js = js + "energyCtx.fillStyle = '#e0e0e0';"
  js = js + "energyCtx.font = '14px monospace';"
  js = js + "energyCtx.fillText('Energy Conservation', 130, 20);"
  js = js + "energyCtx.fillText('Initial: ' + energyData[0].toFixed(2), 10, 290);"
  js = js + "energyCtx.fillText('Current: ' + energyData[currentFrame].toFixed(2), 130, 290);"
  js = js + "}"

  js = js + "function drawInfoChart() {"
  js = js + "infoCtx.clearRect(0, 0, 400, 300);"
  js = js + "infoCtx.fillStyle = '#16213e';"
  js = js + "infoCtx.fillRect(0, 0, 400, 300);"
  js = js + "infoCtx.fillStyle = '#e0e0e0';"
  js = js + "infoCtx.font = '14px monospace';"
  js = js + "let y = 30;"
  js = js + "for (let p of particleData) {"
  js = js + "let pos = p.positions[currentFrame] || p;"
  js = js + "infoCtx.fillStyle = p.color;"
  js = js + "infoCtx.fillText(p.name + ': (' + pos.x.toFixed(2) + ', ' + pos.y.toFixed(2) + ')', 10, y);"
  js = js + "y += 20;"
  js = js + "}"
  js = js + "infoCtx.fillText('Frame: ' + currentFrame + ' / ' + maxFrames, 10, y + 20);"
  js = js + "infoCtx.fillText('Scale: ' + scale.toFixed(1), 10, y + 40);"
  js = js + "}"

  js = js + "function updateLegend() {"
  js = js + "let html = '';"
  js = js + "for (let p of particleData) {"
  js = js + "html += '<span style=\"color:' + p.color + '\">■</span> ' + p.name + '  ';"
  js = js + "}"
  js = js + "document.getElementById('legend').innerHTML = html;"
  js = js + "}"

  js = js + "function updateTrail(name, x, y) {"
  js = js + "if (!trailHistory[name]) trailHistory[name] = [];"
  js = js + "trailHistory[name].push({x, y});"
  js = js + "if (trailHistory[name].length > 200) trailHistory[name].shift();"
  js = js + "}"

  js = js + "function playPause() {"
  js = js + "isPlaying = !isPlaying;"
  js = js + "if (isPlaying) {"
  js = js + "playInterval = setInterval(() => {"
  js = js + "currentFrame = (currentFrame + 1) % maxFrames;"
  js = js + "timeSlider.value = currentFrame;"
  js = js + "timeDisplay.textContent = currentFrame;"
  js = js + "draw();"
  js = js + "}, 50);"
  js = js + "} else {"
  js = js + "clearInterval(playInterval);"
  js = js + "}"
  js = js + "}"

  js = js + "function resetView() {"
  js = js + "scale = 20;"
  js = js + "offsetX = canvas.width / 2;"
  js = js + "offsetY = canvas.height / 2;"
  js = js + "draw();"
  js = js + "}"

  js = js + "function toggleTrails() {"
  js = js + "showTrails = !showTrails;"
  js = js + "document.querySelector('button:nth-child(4)').textContent = 'Trails: ' + (showTrails ? 'ON' : 'OFF');"
  js = js + "draw();"
  js = js + "}"

  js = js + "timeSlider.addEventListener('input', (e) => {"
  js = js + "currentFrame = parseInt(e.target.value);"
  js = js + "timeDisplay.textContent = currentFrame;"
  js = js + "draw();"
  js = js + "});"

  js = js + "canvas.addEventListener('wheel', (e) => {"
  js = js + "e.preventDefault();"
  js = js + "let zoom = e.deltaY > 0 ? 0.9 : 1.1;"
  js = js + "let mouse = { x: e.offsetX, y: e.offsetY };"
  js = js + "let worldBefore = screenToWorld(mouse.x, mouse.y);"
  js = js + "scale *= zoom;"
  js = js + "scale = Math.max(1, Math.min(scale, 200));"
  js = js + "let worldAfter = screenToWorld(mouse.x, mouse.y);"
  js = js + "offsetX += (worldBefore.x - worldAfter.x) * scale;"
  js = js + "offsetY += (worldBefore.y - worldAfter.y) * scale;"
  js = js + "draw();"
  js = js + "});"

  js = js + "canvas.addEventListener('mousedown', (e) => {"
  js = js + "isPanning = true;"
  js = js + "lastMouseX = e.clientX;"
  js = js + "lastMouseY = e.clientY;"
  js = js + "});"

  js = js + "canvas.addEventListener('mousemove', (e) => {"
  js = js + "if (!isPanning) return;"
  js = js + "let dx = e.clientX - lastMouseX;"
  js = js + "let dy = e.clientY - lastMouseY;"
  js = js + "offsetX += dx;"
  js = js + "offsetY -= dy;"
  js = js + "lastMouseX = e.clientX;"
  js = js + "lastMouseY = e.clientY;"
  js = js + "draw();"
  js = js + "});"

  js = js + "canvas.addEventListener('mouseup', () => { isPanning = false; });"
  js = js + "canvas.addEventListener('mouseleave', () => { isPanning = false; });"

  js = js + "// Touch support"
  js = js + "canvas.addEventListener('touchstart', (e) => {"
  js = js + "e.preventDefault();"
  js = js + "isPanning = true;"
  js = js + "lastMouseX = e.touches[0].clientX;"
  js = js + "lastMouseY = e.touches[0].clientY;"
  js = js + "});"

  js = js + "canvas.addEventListener('touchmove', (e) => {"
  js = js + "e.preventDefault();"
  js = js + "if (!isPanning) return;"
  js = js + "let dx = e.touches[0].clientX - lastMouseX;"
  js = js + "let dy = e.touches[0].clientY - lastMouseY;"
  js = js + "offsetX += dx;"
  js = js + "offsetY -= dy;"
  js = js + "lastMouseX = e.touches[0].clientX;"
  js = js + "lastMouseY = e.touches[0].clientY;"
  js = js + "draw();"
  js = js + "});"

  js = js + "canvas.addEventListener('touchend', () => { isPanning = false; });"

  js = js + "// Pinch zoom"
  js = js + "canvas.addEventListener('touchmove', (e) => {"
  js = js + "if (e.touches.length === 2) {"
  js = js + "e.preventDefault();"
  js = js + "let dx = e.touches[0].clientX - e.touches[1].clientX;"
  js = js + "let dy = e.touches[0].clientY - e.touches[1].clientY;"
  js = js + "let dist = Math.sqrt(dx*dx + dy*dy);"
  js = js + "if (window.lastTouchDist) {"
  js = js + "let zoom = dist / window.lastTouchDist;"
  js = js + "scale *= zoom;"
  js = js + "scale = Math.max(1, Math.min(scale, 200));"
  js = js + "draw();"
  js = js + "}"
  js = js + "window.lastTouchDist = dist;"
  js = js + "}"
  js = js + "});"

  js = js + "// Build trail history from particle data"
  js = js + "for (let i = 0; i < maxFrames; i++) {"
  js = js + "for (let p of particleData) {"
  js = js + "let pos = p.positions[i];"
  js = js + "if (pos) updateTrail(p.name, pos.x, pos.y);"
  js = js + "}"
  js = js + "}"

  js = js + "// Initial draw"
  js = js + "draw();"
  js = js + "</script>"

  html_page(title, body, js)

# ── Rocket Visualization ──
# Creates an HTML page showing rocket cross-section, thrust curve, and trajectory

fn rocket_viz_html(rocket_data, trajectory_data, thrust_data, title)
  let body = "<div class='container'>"
  body = body + "<div class='chart-box'>"
  body = body + "<canvas id='rocketCanvas' width='300' height='500'></canvas>"
  body = body + "</div>"
  body = body + "<div class='chart-box'>"
  body = body + "<canvas id='thrustChart' width='400' height='300'></canvas>"
  body = body + "</div>"
  body = body + "<div class='chart-box'>"
  body = body + "<canvas id='trajectoryChart' width='400' height='300'></canvas>"
  body = body + "</div>"
  body = body + "</div>"

  let js_data = "const rocketData = " + json_stringify(rocket_data) + ";"
  let js_traj = "const trajectoryData = " + json_stringify(trajectory_data) + ";"
  let js_thrust = "const thrustData = " + json_stringify(thrust_data) + ";"

  let js = "<script>"
  js = js + js_data + js_traj + js_thrust
  js = js + "const rCtx = document.getElementById('rocketCanvas').getContext('2d');"
  js = js + "const thrustCtx = document.getElementById('thrustChart').getContext('2d');"
  js = js + "const trajCtx = document.getElementById('trajectoryChart').getContext('2d');"
  js = js + "function drawRocket() {"
  js = js + "rCtx.clearRect(0, 0, 300, 500);"
  js = js + "let y = 450;"
  js = js + "const stages = rocketData.stages || [];"
  js = js + "for (let i = 0; i < stages.length; i++) {"
  js = js + "const s = stages[i];"
  js = js + "const h = 80;"
  js = js + "const w = 40;"
  js = js + "rCtx.fillStyle = s.color || '#e94560';"
  js = js + "rCtx.fillRect(130, y - h, w, h);"
  js = js + "rCtx.strokeStyle = '#fff';"
  js = js + "rCtx.lineWidth = 2;"
  js = js + "rCtx.strokeRect(130, y - h, w, h);"
  js = js + "rCtx.fillStyle = '#aaa';"
  js = js + "rCtx.fillRect(140, y, 20, 20);"
  js = js + "rCtx.fillStyle = '#fff';"
  js = js + "rCtx.font = '12px monospace';"
  js = js + "rCtx.fillText(s.name + ' (m=' + s.mass + 'kg)', 10, y - h + 15);"
  js = js + "rCtx.fillText('Isp=' + s.isp + 's', 10, y - h + 30);"
  js = js + "y -= h + 10;"
  js = js + "}"
  js = js + "rCtx.fillStyle = '#00d4ff';"
  js = js + "rCtx.fillRect(140, y, 20, 30);"
  js = js + "rCtx.strokeStyle = '#fff';"
  js = js + "rCtx.strokeRect(140, y, 20, 30);"
  js = js + "rCtx.fillStyle = '#fff';"
  js = js + "rCtx.fillText('Payload: ' + rocketData.payload + 'kg', 10, y + 15);"
  js = js + "}"
  js = js + "function drawThrustChart() {"
  js = js + "thrustCtx.clearRect(0, 0, 400, 300);"
  js = js + "thrustCtx.fillStyle = '#16213e';"
  js = js + "thrustCtx.fillRect(0, 0, 400, 300);"
  js = js + "if (thrustData.length < 2) return;"
  js = js + "let maxT = 0;"
  js = js + "for (let d of thrustData) { if (d.thrust > maxT) maxT = d.thrust; }"
  js = js + "if (maxT === 0) maxT = 1;"
  js = js + "thrustCtx.strokeStyle = '#00d4ff';"
  js = js + "thrustCtx.lineWidth = 2;"
  js = js + "thrustCtx.beginPath();"
  js = js + "for (let i = 0; i < thrustData.length; i++) {"
  js = js + "const x = 40 + (i / (thrustData.length - 1)) * 340;"
  js = js + "const y = 270 - (thrustData[i].thrust / maxT) * 220;"
  js = js + "if (i === 0) thrustCtx.moveTo(x, y);"
  js = js + "else thrustCtx.lineTo(x, y);"
  js = js + "}"
  js = js + "thrustCtx.stroke();"
  js = js + "thrustCtx.fillStyle = '#e0e0e0';"
  js = js + "thrustCtx.font = '14px monospace';"
  js = js + "thrustCtx.fillText('Thrust Curve (N)', 150, 20);"
  js = js + "}"
  js = js + "function drawTrajectory() {"
  js = js + "trajCtx.clearRect(0, 0, 400, 300);"
  js = js + "trajCtx.fillStyle = '#16213e';"
  js = js + "trajCtx.fillRect(0, 0, 400, 300);"
  js = js + "if (trajectoryData.length < 2) return;"
  js = js + "let maxAlt = 0; let maxVel = 0; let maxTime = 0;"
  js = js + "for (let d of trajectoryData) {"
  js = js + "if (d.altitude > maxAlt) maxAlt = d.altitude;"
  js = js + "if (d.velocity > maxVel) maxVel = d.velocity;"
  js = js + "if (d.time > maxTime) maxTime = d.time;"
  js = js + "}"
  js = js + "if (maxAlt === 0) maxAlt = 1;"
  js = js + "if (maxVel === 0) maxVel = 1;"
  js = js + "if (maxTime === 0) maxTime = 1;"
  js = js + "trajCtx.strokeStyle = '#e94560';"
  js = js + "trajCtx.lineWidth = 2;"
  js = js + "trajCtx.beginPath();"
  js = js + "for (let i = 0; i < trajectoryData.length; i++) {"
  js = js + "const x = 40 + (trajectoryData[i].time / maxTime) * 340;"
  js = js + "const y = 270 - (trajectoryData[i].altitude / maxAlt) * 220;"
  js = js + "if (i === 0) trajCtx.moveTo(x, y);"
  js = js + "else trajCtx.lineTo(x, y);"
  js = js + "}"
  js = js + "trajCtx.stroke();"
  js = js + "trajCtx.strokeStyle = '#00d4ff';"
  js = js + "trajCtx.beginPath();"
  js = js + "for (let i = 0; i < trajectoryData.length; i++) {"
  js = js + "const x = 40 + (trajectoryData[i].time / maxTime) * 340;"
  js = js + "const y = 270 - (trajectoryData[i].velocity / maxVel) * 220;"
  js = js + "if (i === 0) trajCtx.moveTo(x, y);"
  js = js + "else trajCtx.lineTo(x, y);"
  js = js + "}"
  js = js + "trajCtx.stroke();"
  js = js + "trajCtx.fillStyle = '#e0e0e0';"
  js = js + "trajCtx.font = '14px monospace';"
  js = js + "trajCtx.fillText('Trajectory (red=alt, blue=vel)', 100, 20);"
  js = js + "}"
  js = js + "drawRocket();"
  js = js + "drawThrustChart();"
  js = js + "drawTrajectory();"
  js = js + "</script>"

  html_page(title, body, js)

# ── Flight Visualization ──
# Creates an HTML page showing airplane flight dynamics

fn flight_viz_html(flight_data, title)
  let body = "<div class='chart-box'>"
  body = body + "<canvas id='flightCanvas' width='600' height='400'></canvas>"
  body = body + "</div>"

  let js_data = "const flightData = " + json_stringify(flight_data) + ";"

  let js = "<script>"
  js = js + js_data
  js = js + "const canvas = document.getElementById('flightCanvas');"
  js = js + "const ctx = canvas.getContext('2d');"
  js = js + "function draw() {"
  js = js + "ctx.clearRect(0, 0, 600, 400);"
  js = js + "const grad = ctx.createLinearGradient(0, 0, 0, 300);"
  js = js + "grad.addColorStop(0, '#4a90d9');"
  js = js + "grad.addColorStop(1, '#87ceeb');"
  js = js + "ctx.fillStyle = grad;"
  js = js + "ctx.fillRect(0, 0, 600, 300);"
  js = js + "ctx.fillStyle = '#2d5016';"
  js = js + "ctx.fillRect(0, 300, 600, 100);"
  js = js + "if (flightData.length < 2) return;"
  js = js + "let maxAlt = 0;"
  js = js + "for (let d of flightData) { if (d.altitude > maxAlt) maxAlt = d.altitude; }"
  js = js + "if (maxAlt === 0) maxAlt = 1;"
  js = js + "ctx.strokeStyle = '#fff';"
  js = js + "ctx.lineWidth = 2;"
  js = js + "ctx.beginPath();"
  js = js + "for (let i = 0; i < flightData.length; i++) {"
  js = js + "const x = 40 + (i / (flightData.length - 1)) * 500;"
  js = js + "const y = 290 - (flightData[i].altitude / maxAlt) * 200;"
  js = js + "if (i === 0) ctx.moveTo(x, y);"
  js = js + "else ctx.lineTo(x, y);"
  js = js + "}"
  js = js + "ctx.stroke();"
  js = js + "const last = flightData[flightData.length - 1];"
  js = js + "const ax = 40 + ((flightData.length - 1) / (flightData.length - 1)) * 500;"
  js = js + "const ay = 290 - (last.altitude / maxAlt) * 200;"
  js = js + "ctx.save();"
  js = js + "ctx.translate(ax, ay);"
  js = js + "ctx.fillStyle = '#ff6b6b';"
  js = js + "ctx.beginPath();"
  js = js + "ctx.moveTo(0, 0);"
  js = js + "ctx.lineTo(-20, 10);"
  js = js + "ctx.lineTo(20, 0);"
  js = js + "ctx.lineTo(-20, -10);"
  js = js + "ctx.closePath();"
  js = js + "ctx.fill();"
  js = js + "ctx.restore();"
  js = js + "ctx.fillStyle = '#fff';"
  js = js + "ctx.font = '14px monospace';"
  js = js + "ctx.fillText('Flight: ' + last.name, 10, 20);"
  js = js + "ctx.fillText('Alt: ' + last.altitude + 'm  Speed: ' + last.velocity + 'm/s', 10, 40);"
  js = js + "ctx.fillText('AoA: ' + last.alpha + 'rad  Lift: ' + last.lift + 'N', 10, 60);"
  js = js + "}"
  js = js + "draw();"
  js = js + "</script>"

  html_page(title, body, js)

# ── Serve Visualization ──
# Starts a web server to serve the visualization

fn serve_viz(html_content, port)
  say("Starting visualization server on port " + str(port))
  say("Open http://localhost:" + str(port) + " in your browser")
  let routes = {
    "/": html_content
  }
  serve(port, routes)

# ── Save Visualization to File ──
# Saves HTML content to a file using json_save

fn save_viz(html_content, filename)
  json_save(filename, {"html": html_content, "type": "visualization"})
  say("Visualization saved to " + filename + " (as JSON with 'html' field)")
  say("Open the file and extract the 'html' field, or use serve_viz() to serve it live")